### ISSUE TITLE
It seems like you wanted to load some plugins, however they couldn't be loaded

### ISSUE THREAD

**Issue by repl-krishna-g** [bskim45/fastlane-plugin-google_drive#5] opened 2018-12-11 19:36 UTC
Getting below error when I try to add google_drive plugin(`fastlane add_plugin google_drive`)

`DEBUG [2018-12-11 12:32:44.64]: Checking if there are any plugins that should be loaded...
ERROR [2018-12-11 12:32:44.74]: It seems like you wanted to load some plugins, however they couldn't be loaded
ERROR [2018-12-11 12:32:44.74]: Please follow the troubleshooting guide: https://docs.fastlane.tools/plugins/plugins-troubleshooting/
DEBUG [2018-12-11 12:32:45.33]: Adding line: gem 'fastlane-plugin-google_drive'
INFO [2018-12-11 12:32:45.33]: Plugin 'fastlane-plugin-google_drive' was added to './fastlane/Pluginfile'
WARN [2018-12-11 12:32:45.33]: Make sure to commit your Gemfile, Gemfile.lock and Pluginfile to version control
INFO [2018-12-11 12:32:45.33]: $ bundle install && echo 'Successfully installed plugins'
`

**Comment by bskim45** [comment] 2018-12-27 03:01
It seems like you have a problem with loading previous plugins. Can you reproduce that error with other plugins disabled?

**Comment by dokinkon** [comment] 2019-01-12 04:11
Hi, I got a similar problem while installing this plugin:

[12:04:50]: Error loading plugin 'fastlane-plugin-google_drive': Unable to activate google_drive-2.1.12, because google-api-client-0.23.9 conflicts with google-api-client (< 0.22.0, >= 0.11.0)
[12:04:50]: Error loading plugin 'fastlane-plugin-google_drive': Unable to activate google_drive-2.1.12, because google-api-client-0.23.9 conflicts with google-api-client (< 0.22.0, >= 0.11.0)
[12:04:50]: It seems like you wanted to load some plugins, however they couldn't be loaded
[12:04:50]: Please follow the troubleshooting guide: https://docs.fastlane.tools/plugins/plugins-troubleshooting/
+------------------------+-----------+------------------+
|                     Used plugins                      |
+------------------------+-----------+------------------+
| Plugin                 | Version   | Action           |
+------------------------+-----------+------------------+
| fastlane-plugin-googl  | undefined | No actions found |
| e_drive                |           |                  |
+------------------------+-----------+------------------+

I've tried installing other versions of google-api-client which includes
google-api-client-0.22.0, google-api-client-0.23.9, and google-api-client-0.27.2, but still have this problem. Thanks your kindly reply.

**Comment by bskim45** [comment] 2019-01-14 06:16
ok. seems like there is dependency conflict with other plugins. I'll publish new version with updated dep.

**Comment by bskim45** [comment] 2019-01-14 09:14
Fixed in 0.4.0

**Closed by bskim45** 2019-01-14 09:14 UTC
